[package]
name = "albus-bellman"
version = "0.0.1"
edition = "2021"

[dependencies]
bellman = "0.13"
rand = "0.8"
bls12_381 = "0.7"
groth16 = { path = "../groth16", features = ["std"] }
ff = "0.12"
pairing = "0.22"
