[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.17"

[features]
seeds = false
skip-lint = true

[workspace]
members = [
  "programs/albus",
  "programs/albus-transfer",
  "programs/albus-swap",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/albus.json"

[programs.localnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[programs.devnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[programs.mainnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm test:e2e"

[test]
startup_wait = 10000

[[test.genesis]]
address = "ASP9HnS3MzoVNrRYgr96UMRbsR1xbHa8xPrbJYKxYEZY"
program = "target/deploy/albus_stake_pool.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

### Token Metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
