[toolchain]
# anchor 0.30.0 doesn't work with solita
anchor_version = "0.29.0"
solana_version = "1.18.12"

[features]
seeds = false
skip-lint = false

[workspace]
members = [
  "programs/albus",
  "programs/albus-transfer",
  "programs/albus-swap",
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/albus.json"

[programs.localnet]
albus = "ALBSoqJrZeZZ423xWme5nozNcozCtMvDWTZZmQLMT3fp"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[programs.devnet]
albus = "ALBSoqJrZeZZ423xWme5nozNcozCtMvDWTZZmQLMT3fp"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[programs.mainnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "ASWfaoztykN8Lz1P2uwuvwWR61SvFrvn6acM1sJpxKtq"
albus_transfer = "ATRh9CiamTjKiJ3XcsbxmGtDoeqg6XujUvgPLemEMCBe"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm test:e2e"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # metadata

# `test.validator.clone` does not work for some reason
# solana program dump -u m metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s tests/programs/metaplex_token_metadata_program.so
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/metaplex_token_metadata_program.so"

[[test.genesis]]
address = "ASP9HnS3MzoVNrRYgr96UMRbsR1xbHa8xPrbJYKxYEZY"
program = "target/deploy/albus_stake_pool.so"
