[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.17"

[features]
seeds = false
skip-lint = true

[workspace]
members = [
  "programs/albus",
  "programs/albus-transfer",
  "programs/albus-swap",
]

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet= "./.secrets/upgrade-authority.json"
#wallet = "~/.config/solana/id.json"

[programs.localnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "J8YCNcS2xDvowMcSzWrDYNguk5y9NWfGStNT4YsiKuea"
albus_transfer = "J4pyN7p9dAovEQKoZJV1jUbM3FrCBPLCS2dyiRUnwi5c"

[programs.devnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"
albus_swap = "J8YCNcS2xDvowMcSzWrDYNguk5y9NWfGStNT4YsiKuea"
albus_transfer = "J4pyN7p9dAovEQKoZJV1jUbM3FrCBPLCS2dyiRUnwi5c"

[programs.mainnet]
albus = "ALBUSbdydS2qoQXXeFfr4mqc9LFw5xWmUMdB4tcscHhi"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm test:e2e"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

### Token Metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

### Stake Pool
#[[test.validator.clone]]
#address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
