[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.17"

[features]
seeds = false
skip-lint = false

[workspace]
members = [
  "programs/albus",
]

[provider]
#cluster = "localnet"
cluster = "devnet"
wallet= "./.secrets/upgrade-authority.json"
#wallet = "~/.config/solana/id.json"

[programs.localnet]
albus = "ALBs64hsiHgdg53mvd4bcvNZLfDRhctSVaP7PwAPpsZL"

[programs.devnet]
albus = "ALBs64hsiHgdg53mvd4bcvNZLfDRhctSVaP7PwAPpsZL"

#verified-transfer = "ChfXD6UnExK5ihM1LJcnNGVJekVtHWms5cJu47pH9Fe2"
#verified-swap = "8NHcjkbgyuZzcwryaGJ9zf7JRqKfsHipuNDQdhtk9giR"
#verified-stake = "CMev81L3acPrcTTevCFGdcNQnDypMGzuiAUgo8NBZJzr"
#verified-stake-pool = "HN5hBpR28T8Mjkm1CB1D8Hj5z5rHQ7VkD2ZWmZtFk49e"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm test:e2e"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

### MPL Token Metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

#### SPL Token Program
#[[test.validator.clone]]
#address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
