[workspace]
members = [
  "programs/albus",
  "programs/verified_transfer",
  "packages/albus-verifier"
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = "fat"
panic = "abort"
debug = false
