[workspace]
members = [
#  "programs/*",
  "programs/albus",
#  "packages/solana-verifier",
  "packages/groth16-solana",
]

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
opt-level = "z"
#strip = true
#panic = "abort"

#[profile.release.build-override]
#opt-level = 3
#incremental = false
#codegen-units = 1
