[workspace]
resolver = "2"
members = [
  "programs/*",
  "packages/solana-verifier",
  "packages/groth16-solana",
]

[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = true
opt-level = "z"
#panic = 'abort'
#strip = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
