[workspace]
members = [
#  "programs/*",
  "programs/albus",
  "packages/albus-verifier",
  "packages/groth16-solana",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = "z"
#panic = "abort"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
