edition = "2021"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
# use_small_heuristics = "Max"
use_field_init_shorthand = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
trailing_comma = "Vertical"
