[package]
name = "albus-solana-verifier"
description = "Albus on-chain compliance check"
version = "0.1.2"
edition = "2021"
license = "AGPL-3.0"
keywords = ["albus", "kyc", "did"]
repository = "https://github.com/mfactory-lab/albus"
#readme = "README.md"

[features]
cpi = ["albus", "anchor-lang"]

[dependencies]
arrayref = "^0.3.7"
solana-program = "^1.16"
albus = { path = "../../programs/albus", optional = true, features = ["verify-on-chain"] }
anchor-lang = { version = "0.29.0", optional = true }
