[package]
name = "albus-stake-pool"
version = "0.7.0"
description = "Solana Program Library Stake Pool (Albus Verification)"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []
testing = []
devnet = []

[dependencies]
albus-solana-verifier = { path = "../../packages/solana-verifier" }
arrayref = "0.3.7"
borsh = "0.10"
bytemuck = "1.13"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
serde = "1.0.193"
serde_derive = "1.0.103"
solana-program = "1.17.2"
spl-math = { version = "0.2", features = [ "no-entrypoint" ] }
spl-pod = { version = "0.1", features = ["borsh"] }
spl-token-2022 = { version = "0.9", features = [ "no-entrypoint" ] }
thiserror = "1.0"
bincode = "1.3.1"

[lib]
crate-type = ["cdylib", "lib"]
