[package]
name = "albus"
version = "0.0.1"
license = "Apache-2.0"
description = "Albus program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.27.0" }
anchor-spl = "0.27.0"
#groth16 = { path = "../../groth16", features = ["std"] }
#bls12_381 = "0.7"

