[package]
name = "albus"
version = "0.0.1"
license = "Apache-2.0"
description = "Albus program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.26.0" }
anchor-spl = "0.26.0"
rust_decimal = "1.26"
