[package]
name = "albus"
version = "0.0.7"
description = "Albus Protocol on-chain program"
license = "AGPL-3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
time = "0.3.23"
anchor-lang = { version = "0.28.0", features = ["init-if-needed"]}
anchor-spl = { version = "0.28.0" }
#mpl-token-metadata = { version = "1.13.0", features = ["no-entrypoint"] }
groth16-solana = { path = "../../packages/groth16-solana" }
