[package]
name = "albus"
version = "0.0.2"
license = "Apache-2.0"
description = "Albus Protocol Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
# Fix: https://github.com/solana-labs/solana/issues/30188
#solana-program = "~1.14.16"
anchor-lang = { version = "^0.27", features = ["init-if-needed"]}
anchor-spl = { version = "^0.27" }
mpl-token-metadata = { version = "1.9.1", features = ["no-entrypoint"] }
#winnow = "=0.4.1"
