[package]
name = "albus"
version = "0.0.12"
description = "Albus Protocol on-chain program"
license = "AGPL-3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
verify-on-chain = ["dep:groth16-solana"]
#default = ["verify-on-chain"]

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
#anchor-spl = { version = "0.28.0" }
groth16-solana = { path = "../../packages/groth16-solana", optional = true }
#mpl-token-metadata = { version = "1.13.0", features = ["no-entrypoint"] }
#num-traits = "0.2.16"
time = { version = "0.3.23", default-features = false }
