declare module 'did-context'
declare module 'ed25519-signature-2020-context'
declare module 'x25519-key-agreement-2020-context'
declare module 'credentials-context'
declare module 'jsonld-document-loader'
