// auto-generated by circomkit
pragma circom 2.1.0;

include "../ageProof.circom";

component main {public[timestamp, config, claimsKey, claimsProof, credentialRoot, issuerPk, issuerSignature, trusteePublicKey]} = AgeProof(5, 3, 2);
