// auto-generated by circomkit
pragma circom 2.1.5;

include "../agePolicy.circom";

component main {public[timestamp, minAge, maxAge, credentialRoot, meta_validUntilKey, meta_validUntilProof, birthDateKey, birthDateProof, issuerPk, issuerSignature, trusteePublicKey]} = AgePolicy(5, 3, 2);
