// auto-generated by circomkit
pragma circom 2.1.5;

include "../ageProof.circom";

component main {public[timestamp, ageRange, birthDateKey, birthDateProof, meta_validUntilKey, meta_validUntilProof, credentialRoot, issuerPk, issuerSignature, trusteePublicKey]} = AgeProof(5, 3, 2);
