// auto-generated by circomkit
pragma circom 2.1.5;

include "../aml.circom";

component main {public[timestamp, expectedSpecId, specIdKey, specIdProof, meta_validUntilKey, meta_validUntilProof, credentialRoot, issuerPk, issuerSignature]} = AML(5);
