// auto-generated by circomkit
pragma circom 2.1.0;

include "../kyc.circom";

component main {public[config, timestamp, countryLookup, givenNameKey, givenNameProof, familyNameKey, familyNameProof, birthDateKey, birthDateProof, countryKey, countryProof, docNumberKey, docNumberProof, meta_validUntilKey, meta_validUntilProof, credentialRoot, issuerPk, issuerSignature, trusteePublicKey]} = Kyc(5, 2, 3, 2);
