// auto-generated by circomkit
pragma circom 2.1.0;

include "../kyc.circom";

component main {public[config, timestamp, countryLookup, claimsKey, claimsProof, credentialRoot, issuerPk, issuerSignature, trusteePublicKey]} = Kyc(5, 2, 3, 2);
