// auto-generated by circomkit
pragma circom 2.1.5;

include "../livenessProof.circom";

component main {public[timestamp, expectedType, livenessTypeKey, livenessTypeProof, meta_validUntilKey, meta_validUntilProof, credentialRoot, issuerPk, issuerSignature]} = LivenessProof(4, 1);
