// auto-generated by circomkit
pragma circom 2.1.5;

include "../residenceProof.circom";

component main {public[timestamp, selectionMode, countryLookup, countryKey, countryProof, meta_validUntilKey, meta_validUntilProof, credentialRoot, issuerPk, issuerSignature]} = ResidenceProof(5, 2);
