// auto-generated by circomkit
pragma circom 2.1.5;

include "../typeProof.circom";

component main {public[timestamp, expectedType, claimsKey, claimsProof, credentialRoot, issuerPk, issuerSignature]} = TypeProof(4, 1);
