name: Release(sdk)

on:
  push:
    branches: [ main, dev ]
    paths:
      - packages/albus-sdk/src/**
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      package: @albus-finance/sdk
