name: Release(sdk)

on:
  push:
    branches: [ dev, main ]
    paths:
      - packages/albus-sdk/src/**
  workflow_dispatch:

jobs:
  release:
    name: Reusable
    uses: ./.github/workflows/release.yml
    with:
      package: "@albus-finance/sdk"
      github_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
