name: Release(transfer-sdk)

on:
  push:
    branches: [ dev ]
    paths:
      - packages/albus-transfer-sdk/src/**
  workflow_dispatch:

jobs:
  release-transfer-sdk:
    name: Reusable
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      package: "@albus-finance/transfer-sdk"
