name: Release(core)

on:
  push:
    branches: [ main ]
    paths:
      - packages/albus-core/src/**
  workflow_dispatch:

jobs:
  release:
    name: Reusable
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      package: "@albus-finance/core"
