name: Release

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

env:
  PACKAGE: ${{ inputs.package }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Initialize the NPM config
        run: pnpm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.email "release@albus.finance"
          git config --global user.name "release-it-bot"

      - name: Run release
        run: |
          pnpm -F ${{ env.PACKAGE }}... build
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            pnpm -F ${{ env.PACKAGE }} release:ci
          else
            pnpm -F ${{ env.PACKAGE }} release:pre
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
