name: Release(swap-sdk)

on:
  push:
    branches: [dev]
    paths:
      - packages/albus-swap-sdk/src/**
  workflow_dispatch:

jobs:
  release-swap-sdk:
    name: Reusable
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      package: '@albus-finance/swap-sdk'
