name: Release

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      github_token:
        required: true
        type: string
      npm_token:
        required: true
        type: string

env:
  PACKAGE: ${{ inputs.package }}
  GITHUB_TOKEN: ${{ inputs.github_token }}
  NPM_TOKEN: ${{ inputs.npm_token }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm install

      - name: Initialize the NPM config
        run: pnpm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Setup git
        run: |
          git config --global user.name "release-it-bot"

      - name: Run release
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            pnpm -F ${{ env.PACKAGE }} release:ci
          else
            pnpm -F ${{ env.PACKAGE }} release:pre
          fi
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

