name: Release(sdk)

on:
  push:
    branches: [ dev, main ]
    paths:
      - packages/albus-sdk/src/**
  workflow_dispatch:

jobs:
  release:
    name: Reusable
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      package: "@albus-finance/sdk"
