name: Test(e2e)

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-solana/

      - uses: actions/cache@v3
        if: ${{ env.CACHE != 'false' }}
        name: target cache
        id: cache-target
        with:
          path: ./target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - run: make test
